[package]
name = "podcast"
version = "0.5.4"
authors = ["Nathan Jaremko <njaremko@gmail.com>"]
description = "A command line podcast manager"
license = "GPL-3.0"
readme = "README.md"
keywords = ["audio", "cli", "podcast", "music"]
repository = "https://github.com/njaremko/podcast"
categories = ["command-line-utilities"]

[badges]
travis-ci = { repository = "njaremko/podcast" }

[[bin]]
bench = false
path = "src/main.rs"
name = "podcast"

[dependencies]
chrono = { version = "0.4", features = ["serde"] }
clap = "2.28"
error-chain = "0.11"
rayon = "0.9"
regex = "0.2"
reqwest = "0.8"
rss = {version = "1.2", features = ["from_url"] }
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
yaml-rust = "0.3"
toml = "0.4"
