[package]
name = "podcast"
version = "0.4.1"
authors = ["njaremko <njaremko@gmail.com>"]
description = "A command line podcast player"
license = "GPL-3.0"
readme = "README.md"
keywords = ["audio", "cli", "podcast", "music"]
repository = "https://github.com/njaremko/podcast"

[dependencies]
chrono = { version = "0.4", features = ["serde"] }
clap = "2.28"
rayon = "0.9"
regex = "0.2"
reqwest = "0.8"
rss = {version = "1.2", features = ["from_url"] }
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
yaml-rust = "0.3"
toml = "0.4"
